typescript:
  - iridium:
    # https://www.npmjs.com/package/iridium?activeTab=versions
    - 7.2.4
    - 7.2.1
    - 7.2.0
    - 7.1.3
  - react-skeletor:
    # https://www.npmjs.com/package/react-skeletor?activeTab=versions
    - 1.0.1
    - 1.0.0
  - use-react-router:
    # https://www.npmjs.com/package/use-react-router?activeTab=versions
    - 1.0.6
  - child_process:
    # https://www.npmjs.com/package/child_process?activeTab=versions
    - 1.0.2
  - express:
    # https://www.npmjs.com/package/express?activeTab=versions
    - 4.18.1
    - 4.18.0
    - 4.17.3
    - 4.17.2
    - 4.17.1
    - 4.17.0
  - fs-extra:
    # https://www.npmjs.com/package/fs-extra?activeTab=versions
    - 11.1.0
    - 11.0.0
  - node-serialize:
    # https://www.npmjs.com/package/node-serialize?activeTab=versions
    - 0.0.4
  - should:
    # https://www.npmjs.com/package/should?activeTab=versions
    - 13.2.3
    - 13.2.2
    - 13.2.1
    - 13.2.0
  - chai:
    # https://www.npmjs.com/package/chai?activeTab=versions
    - 4.3.7
    - 4.3.6
    - 4.3.5
    - 4.3.4
    - 4.3.3
  - mocha:
    # https://www.npmjs.com/package/mocha?activeTab=versions
    - 10.2.0
    - 10.1.0
    - 10.0.0
    - 9.2.2
    - 9.2.1
    - 9.2.0
  - supertest:
    # https://www.npmjs.com/package/supertest?activeTab=versions
    - 6.3.3
    - 6.3.2
    - 6.3.1
    - 6.2.4